// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'card.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Card _$CardFromJson(Map<String, dynamic> json) {
  return Card(
    connectedCardId: json['connected_card_id'] as String,
    accountCardId: json['ACCOUNT_CARD_ID'] as String,
    cardType: json['CARD_TYPE'] as String,
    lastFourDigits: json['LAST_FOUR_DIGITS'] as String,
    cardName: json['CARD_NAME'],
    verifiedStatus: json['VERIFIED_STATUS'] as String,
    verifiedDate: json['VERIFIED_DATE'],
    peopleId: json['PEOPLE_ID'] as String,
    dateAdded: json['DATE_ADDED'] == null
        ? null
        : DateTime.parse(json['DATE_ADDED'] as String),
    bankOfIssue: json['BANK_OF_ISSUE'],
    typeOf: json['TYPE_OF'] as String,
    bvn: json['BVN'],
    bankId: json['BANK_ID'],
    attachmentId: json['ATTACHMENT_ID'],
    expiryDate: json['EXPIRY_DATE'] as String,
    cvv2: json['CVV2'],
    cardNumber: json['CARD_NUMBER'],
    isDefault: json['IS_DEFAULT'] as String,
    cardFirstName: json['CARD_FIRST_NAME'],
    cardLastName: json['CARD_LAST_NAME'],
    expMonth: json['EXP_MONTH'] as String,
    expYear: json['EXP_YEAR'] as String,
    lenderId: json['LENDER_ID'] as String,
    fullExpiryDate: json['FULL_EXPIRY_DATE'],
    bvnCode: json['BVN_CODE'],
    verifyAccount: json['VERIFY_ACCOUNT'] as String,
    verifyName: json['VERIFY_NAME'] as String,
    dateVerified: json['DATE_VERIFIED'],
    bankLogo: json['BANK_LOGO'],
    recurrentBillingToken: json['RECURRENT_BILLING_TOKEN'],
    isInv: json['IS_INV'] as String,
    cardCheckId: json['CARD_CHECK_ID'],
    cardResolved: json['CARD_RESOLVED'] as String,
    paystackAuthorizationCode: json['PAYSTACK_AUTHORIZATION_CODE'] as String,
    cardValidatedThrough: json['CARD_VALIDATED_THROUGH'] as String,
    isSevenHundred: json['IS_SEVEN_HUNDRED'] as String,
    isTest: json['IS_TEST'] as String,
    last4: json['last4'] as String,
    expiry_date: json['expiry_date'] as String,
    brand: json['brand'] as String,
    bank: json['bank'] as String,
    cardId: json['card_id'] as String,
  );
}

Map<String, dynamic> _$CardToJson(Card instance) => <String, dynamic>{
      'connected_card_id': instance.connectedCardId,
      'ACCOUNT_CARD_ID': instance.accountCardId,
      'CARD_TYPE': instance.cardType,
      'LAST_FOUR_DIGITS': instance.lastFourDigits,
      'CARD_NAME': instance.cardName,
      'VERIFIED_STATUS': instance.verifiedStatus,
      'VERIFIED_DATE': instance.verifiedDate,
      'PEOPLE_ID': instance.peopleId,
      'DATE_ADDED': instance.dateAdded?.toIso8601String(),
      'BANK_OF_ISSUE': instance.bankOfIssue,
      'TYPE_OF': instance.typeOf,
      'BVN': instance.bvn,
      'BANK_ID': instance.bankId,
      'ATTACHMENT_ID': instance.attachmentId,
      'EXPIRY_DATE': instance.expiryDate,
      'CVV2': instance.cvv2,
      'CARD_NUMBER': instance.cardNumber,
      'IS_DEFAULT': instance.isDefault,
      'CARD_FIRST_NAME': instance.cardFirstName,
      'CARD_LAST_NAME': instance.cardLastName,
      'EXP_MONTH': instance.expMonth,
      'EXP_YEAR': instance.expYear,
      'LENDER_ID': instance.lenderId,
      'FULL_EXPIRY_DATE': instance.fullExpiryDate,
      'BVN_CODE': instance.bvnCode,
      'VERIFY_ACCOUNT': instance.verifyAccount,
      'VERIFY_NAME': instance.verifyName,
      'DATE_VERIFIED': instance.dateVerified,
      'BANK_LOGO': instance.bankLogo,
      'RECURRENT_BILLING_TOKEN': instance.recurrentBillingToken,
      'IS_INV': instance.isInv,
      'CARD_CHECK_ID': instance.cardCheckId,
      'CARD_RESOLVED': instance.cardResolved,
      'PAYSTACK_AUTHORIZATION_CODE': instance.paystackAuthorizationCode,
      'CARD_VALIDATED_THROUGH': instance.cardValidatedThrough,
      'IS_SEVEN_HUNDRED': instance.isSevenHundred,
      'IS_TEST': instance.isTest,
      'last4': instance.last4,
      'expiry_date': instance.expiry_date,
      'brand': instance.brand,
      'bank': instance.bank,
      'card_id': instance.cardId,
    };
