// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'card.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Card _$CardFromJson(Map<String, dynamic> json) {
  return Card(
    json['connected_card_id'] as String,
    json['ACCOUNT_CARD_ID'] as String,
    json['CARD_TYPE'] as String,
    json['LAST_FOUR_DIGITS'] as String,
    json['CARD_NAME'],
    json['VERIFIED_STATUS'] as String,
    json['VERIFIED_DATE'],
    json['PEOPLE_ID'] as String,
    json['DATE_ADDED'] == null
        ? null
        : DateTime.parse(json['DATE_ADDED'] as String),
    json['BANK_OF_ISSUE'],
    json['TYPE_OF'] as String,
    json['BVN'],
    json['BANK_ID'],
    json['ATTACHMENT_ID'],
    json['EXPIRY_DATE'] as String,
    json['CVV2'],
    json['CARD_NUMBER'],
    json['IS_DEFAULT'] as String,
    json['CARD_FIRST_NAME'],
    json['CARD_LAST_NAME'],
    json['EXP_MONTH'] as String,
    json['EXP_YEAR'] as String,
    json['LENDER_ID'] as String,
    json['FULL_EXPIRY_DATE'],
    json['BVN_CODE'],
    json['VERIFY_ACCOUNT'] as String,
    json['VERIFY_NAME'] as String,
    json['DATE_VERIFIED'],
    json['BANK_LOGO'],
    json['RECURRENT_BILLING_TOKEN'],
    json['IS_INV'] as String,
    json['CARD_CHECK_ID'],
    json['CARD_RESOLVED'] as String,
    json['PAYSTACK_AUTHORIZATION_CODE'] as String,
    json['CARD_VALIDATED_THROUGH'] as String,
    json['IS_SEVEN_HUNDRED'] as String,
    json['IS_TEST'] as String,
    json['last4'] as String,
    json['expiry_date'] as String,
    json['brand'] as String,
    json['bank'] as String,
    json['card_id'] as String,
  );
}

Map<String, dynamic> _$CardToJson(Card instance) => <String, dynamic>{
      'connected_card_id': instance.connectedCardId,
      'ACCOUNT_CARD_ID': instance.accountCardId,
      'CARD_TYPE': instance.cardType,
      'LAST_FOUR_DIGITS': instance.lastFourDigits,
      'CARD_NAME': instance.cardName,
      'VERIFIED_STATUS': instance.verifiedStatus,
      'VERIFIED_DATE': instance.verifiedDate,
      'PEOPLE_ID': instance.peopleId,
      'DATE_ADDED': instance.dateAdded?.toIso8601String(),
      'BANK_OF_ISSUE': instance.bankOfIssue,
      'TYPE_OF': instance.typeOf,
      'BVN': instance.bvn,
      'BANK_ID': instance.bankId,
      'ATTACHMENT_ID': instance.attachmentId,
      'EXPIRY_DATE': instance.expiryDate,
      'CVV2': instance.cvv2,
      'CARD_NUMBER': instance.cardNumber,
      'IS_DEFAULT': instance.isDefault,
      'CARD_FIRST_NAME': instance.cardFirstName,
      'CARD_LAST_NAME': instance.cardLastName,
      'EXP_MONTH': instance.expMonth,
      'EXP_YEAR': instance.expYear,
      'LENDER_ID': instance.lenderId,
      'FULL_EXPIRY_DATE': instance.fullExpiryDate,
      'BVN_CODE': instance.bvnCode,
      'VERIFY_ACCOUNT': instance.verifyAccount,
      'VERIFY_NAME': instance.verifyName,
      'DATE_VERIFIED': instance.dateVerified,
      'BANK_LOGO': instance.bankLogo,
      'RECURRENT_BILLING_TOKEN': instance.recurrentBillingToken,
      'IS_INV': instance.isInv,
      'CARD_CHECK_ID': instance.cardCheckId,
      'CARD_RESOLVED': instance.cardResolved,
      'PAYSTACK_AUTHORIZATION_CODE': instance.paystackAuthorizationCode,
      'CARD_VALIDATED_THROUGH': instance.cardValidatedThrough,
      'IS_SEVEN_HUNDRED': instance.isSevenHundred,
      'IS_TEST': instance.isTest,
      'last4': instance.last4,
      'expiry_date': instance.expiry_date,
      'brand': instance.brand,
      'bank': instance.bank,
      'card_id': instance.cardId,
    };
