// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'investment_product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

InvestmentProduct _$InvestmentProductFromJson(Map<String, dynamic> json) {
  return InvestmentProduct(
    investmentProductId: json['INVESTMENT_PRODUCT_ID'] as String,
    investmentCategoryId: json['INVESTMENT_CATEGORY_ID'] as String,
    lenderId: json['LENDER_ID'] as String,
    dateAdded: json['DATE_ADDED'] as String,
    disbursementAccountId: json['DISBURSEMENT_ACCOUNT_ID'] as String,
    addedBy: json['ADDED_BY'] as String,
    dateModified: json['DATE_MODIFIED'] as String,
    startingAmount: json['STARTING_AMOUNT'] as String,
    investmentAmount: json['INVESTMENT_AMOUNT'] as String,
    tenor: json['TENOR'] as String,
    investmentPeriodicId: json['INVESTMENT_PERIODIC_ID'] as String,
    investmentCurrencyId: json['INVESTMENT_CURRENCY_ID'] as String,
    periodicContribution: json['PERIODIC_CONTRIBUTION'] as String,
    status: json['STATUS'],
    interest: json['INTEREST'] as String,
    interestPeriodId: json['INTEREST_PERIOD_ID'] as String,
    icon: json['ICON'],
    slug: json['SLUG'] as String,
    investmentTitle: json['INVESTMENT_TITLE'] as String,
    investmentDescription: json['INVESTMENT_DESCRIPTION'] as String,
    isPublished: json['IS_PUBLISHED'] as String,
    investmentMaxAmount: json['INVESTMENT_MAX_AMOUNT'] as String,
    maxInvestmentDuration: json['MAX_INVESTMENT_DURATION'] as String,
    daysPerYear: json['DAYS_PER_YEAR'] as String,
    investmentOfficer: json['INVESTMENT_OFFICER'] as String,
    discountType: json['DISCOUNT_TYPE'] as String,
    accrualFrequency: json['ACCRUAL_FREQUENCY'] as String,
    frequencyOfContribution: json['FREQUENCY_OF_CONTRIBUTION'] as String,
    investmentRateTypeId: json['INTEREST_RATE_TYPE_ID'] as String,
    repaymentTypeId: json['REPAYMENT_TYPE_ID'] as String,
    repaymentFrequency: json['REPAYMENT_FREQUENCY'] as String,
    maxBorrowerSalary: json['MAX_BORROWER_SALARY'] as String,
    hasSecurityDeposit: json['HAS_SECURITY_DEPOSIT'] as String,
    securityDeposit: json['SECURITY_DEPOSIT'],
    securityDepositInterest: json['SECURITY_DEPOSIT_INTEREST'],
    securityDepositEarnsInterest: json['SECURITY_DEPOSIT_EARNS_INTEREST'],
    loanSecurityNeeded: json['LOAN_SECUIRTY_NEEDED'],
    loanSecurity: json['LOAN_SECURITY'] as String,
    charges: json['CHARGES'],
    fines: json['FINES'],
    validCardRequired: json['VALID_CARD_REQUIRED'],
    repaymentCycle: json['REPAYMENT_CYCLE'],
    maxNumRepayments: json['MAX_NUM_REPAYMENTS'],
    minNumRepayments: json['MIN_NUM_REPAYMENTS'],
    repaymentSource: json['REPAYMENT_SOURCE'],
    disbursementMode: json['DISBURSEMENT_MODE'] as String,
    installmentFrequency: json['INSTALLMENT_FREQUENCY'],
    gracePeriod: json['GRACE_PERIOD'],
    isVanilla: json['IS_VANILLA'],
    loanOfficer: json['LOAN_OFFICER'],
    disbursementDateType: json['DISBURSEMENT_DATE_TYPE'] as String,
    disbursementDatePlus: json['DISBURSEMENT_DATE_PLUS'] as String,
    disbursementBank: json['DISBURSEMENT_BANK'] as String,
    gracePeriodType: json['GRACE_PERIOD_TYPE'],
    emailMessageTemplates: json['EMAIL_MESSAGE_TEMPLATES'] as String,
    smsMessageTemplates: json['SMS_MESSAGE_TEMPLATES'] as String,
    productCharges: json['PRODUCT_CHARGES'] as String,
    securityDepositDeductible: json['SECURITY_DEPOSIT_DEDUCTIBLE'],
    rollOverCharges: json['ROLLOVER_CHARGES'] as String,
    productFees: json['PRODUCT_FEES'] as String,
    requiredKYC: json['REQUIRED_KYC'] as String,
    collateralDocs: json['COLLATERAL_DOCS'] as String,
    requiredDocs: json['REQUIRED_DOCS'] as String,
    daysPerYear1: json['DAYS_PER_YEAR1'],
    typeOfCredit: json['TYPE_OF_CREDIT'] as String,
    allowRollOver: json['ALLOW_ROLL_OVER'] as String,
    allowMerging: json['ALLOW_MERGING'] as String,
    minRevolvingInstallmentPayment: json['MIN_REVOLVING_INSTALLMENT_PAYMENT'],
    disbursementAccountNumber: json['DISBURSEMENT_ACCOUNT_NUMBER'] as String,
    allowRepaymentAutoDebit: json['ALLOW_REPAYMENT_AUTODEBIT'],
    monthlyPeriod: json['MONTHLY_PERIOD'] as String,
    underWritingTemplate: json['UNDERWRITING_TEMPLATE'] as String,
    requiresInterestUpFront: json['REQUIRES_INTEREST_UPFRONT'],
    compoundingFrequency: json['COMPUNDING_FREQUENCY'] as String,
    investmentGlAccounts: json['INVESTMENT_GL_ACCOUNTS'],
    minSalaryAcceptable: json['MIN_SALARY_ACCEPTABLE'] as String,
    preferredBorrowerGender: json['PREFERRED_BORROWER_GENDER'] as String,
    minimumRatingsId: json['MINIMUM_RATINGS_ID'] as String,
    noOfBankStatements: json['NO_OF_BANK_STATEMENTS'] as String,
    noOfPaySlips: json['NO_OF_PAYSLIPS'] as String,
    minimumGuarantors: json['MINIMUM_GUARANTORS'] as String,
    preferredBorrowerOccupation:
        json['PREFERRED_BORROWER_OCCUPATION'] as String,
    qualifyingDocuments: json['QUALIFYING_DOCUMENTS'] as String,
    preferredOccupationSector: json['PREFERRED_OCCUPATION_SECTOR'] as String,
    guarantorOccupationSector: json['GUARANTOR_OCCUPATION_SECTOR'] as String,
    periodicContributionMax: json['PERIODIC_CONTRIBUTION_MAX'] as String,
    scheduleType: json['SCHEDULE_TYPE'] as String,
    isWeb: json['IS_WEB'] as String,
    isMobile: json['IS_MOBILE'] as String,
    isEditable: json['IS_EDITABLE'] as String,
    assignLoanOfficer: json['ASSIGN_LOAN_OFFICER'] as String,
    loanInterval: json['LOAN_INTERVAL'] as String,
    durationInterval: json['DURATION_INTERVAL'] as String,
    investmentSubCategoryId: json['INVESTMENT_SUB_CATEGORY_ID'] as String,
    applyPenalty: json['APPLY_PENALTY'] as String,
    penaltyType: json['PENALTY_TYPE'] as String,
    penaltyValue: json['PENALTY_VALUE'] as String,
    isDefault: json['IS_DEFAULT'] as String,
    defaultDocs: json['DEFAULT_DOCS'],
    qualifyingDocumentsLoanOptions: json['QUALIFYING_DOCUMENTSLOAN_OPTIONS'],
    mustNotifyAccountOfficer: json['MUST_NOTIFY_ACCOUNT_OFFICER'],
    enableGeoTagging: json['ENABLE_GEOTAGGING'] as String,
    gpsRetry: json['GPS_RETRY'] as String,
    mustNotifyAccountOfficer2: json['MUST_NOFITY_ACCOUNT_OFFICER'] as String,
    notificationEmail: json['NOTIFICATION_EMAIL'],
    loanOptions: json['LOAN_OPTIONS'],
    productType: json['PRODUCT_TYPE'] as String,
    interestCalculationFrequency:
        json['INTEREST_CALCULATION_FREQUENCY'] as String,
    compoundingFrequency1: json['COMPOUNDING_FREQUENCY'] as String,
    minimumInterestBalance: json['MINIMUM_INTEREST_BALANCE'] as String,
    hasInsurance: json['HAS_INSURANCE'] as String,
    insuranceProvider: json['INSURANCE_PROVIDER'] as String,
    availableUnits: json['AVAILABLE_UNITS'] as String,
    startDate: json['START_DATE'],
    endDate: json['END_DATE'],
    offerClosingDate: json['OFFER_CLOSING_DATE'],
    attachments: json['ATTACHMENTS'],
    applyBonus: json['APPLY_BONUS'] as String,
    bonusType: json['BONUS_TYPE'] as String,
    enableTopUp: json['ENABLE_TOP_UP'] as String,
    enableWithdrawal: json['ENABLE_WITHDRAWAL'] as String,
    enableRollover: json['ENABLE_ROLLOVER'] as String,
    maxWithdrawalPercentage: json['MAX_WITHDRAWAL_PERCENTAGE'] as String,
    signatureEnabled: json['signature_enabled'],
    signatureLeftEnabled: json['signature_left_enabled'],
    offerBody: json['offer_body'],
    dateVisible: json['date_visible'],
    offerLetterName: json['offer_letter_name'],
    offerLetterLogo: json['offer_letter_logo'],
    offerLetterAddress: json['offer_letter_address'],
    offerLetterSalutation: json['offer_letter_salutation'],
    offerLetterBody: json['offer_letter_body'],
    offerLetterTerm: json['offer_letter_term'],
    offerLetterRepayment: json['offer_letter_repayment'],
    offerLetterSignature: json['offer_letter_signature'],
    signatureLeft: json['signature_left'],
    signatureRight: json['signature_right'],
    offerLetterSubject: json['offer_letter_subject'],
    offerLetterTags: json['offer_letter_tags'],
    currencyShortCode: json['CURRENCY_SHORT_CODE'] as String,
    ld: json['LD'] as String,
    interestDuration: json['INTEREST_DURATION'] as String,
    adjectival: json['ADJECTIVAL'] as String,
    legalName: json['LEGAL_NAME'] as String,
    abbr: json['ABBREV'] as String,
    tenorRate: (json['tenor_rate'] as List)
        ?.map((e) =>
            e == null ? null : TenorRate.fromJson(e as Map<String, dynamic>))
        ?.toList(),
  );
}

Map<String, dynamic> _$InvestmentProductToJson(InvestmentProduct instance) =>
    <String, dynamic>{
      'INVESTMENT_PRODUCT_ID': instance.investmentProductId,
      'INVESTMENT_CATEGORY_ID': instance.investmentCategoryId,
      'LENDER_ID': instance.lenderId,
      'DATE_ADDED': instance.dateAdded,
      'DISBURSEMENT_ACCOUNT_ID': instance.disbursementAccountId,
      'ADDED_BY': instance.addedBy,
      'DATE_MODIFIED': instance.dateModified,
      'STARTING_AMOUNT': instance.startingAmount,
      'INVESTMENT_AMOUNT': instance.investmentAmount,
      'TENOR': instance.tenor,
      'tenor_rate': instance.tenorRate,
      'INVESTMENT_PERIODIC_ID': instance.investmentPeriodicId,
      'INVESTMENT_CURRENCY_ID': instance.investmentCurrencyId,
      'PERIODIC_CONTRIBUTION': instance.periodicContribution,
      'STATUS': instance.status,
      'INTEREST': instance.interest,
      'INTEREST_PERIOD_ID': instance.interestPeriodId,
      'ICON': instance.icon,
      'SLUG': instance.slug,
      'INVESTMENT_TITLE': instance.investmentTitle,
      'INVESTMENT_DESCRIPTION': instance.investmentDescription,
      'IS_PUBLISHED': instance.isPublished,
      'INVESTMENT_MAX_AMOUNT': instance.investmentMaxAmount,
      'MAX_INVESTMENT_DURATION': instance.maxInvestmentDuration,
      'DAYS_PER_YEAR': instance.daysPerYear,
      'INVESTMENT_OFFICER': instance.investmentOfficer,
      'DISCOUNT_TYPE': instance.discountType,
      'ACCRUAL_FREQUENCY': instance.accrualFrequency,
      'FREQUENCY_OF_CONTRIBUTION': instance.frequencyOfContribution,
      'INTEREST_RATE_TYPE_ID': instance.investmentRateTypeId,
      'REPAYMENT_TYPE_ID': instance.repaymentTypeId,
      'REPAYMENT_FREQUENCY': instance.repaymentFrequency,
      'MAX_BORROWER_SALARY': instance.maxBorrowerSalary,
      'HAS_SECURITY_DEPOSIT': instance.hasSecurityDeposit,
      'SECURITY_DEPOSIT': instance.securityDeposit,
      'SECURITY_DEPOSIT_INTEREST': instance.securityDepositInterest,
      'SECURITY_DEPOSIT_EARNS_INTEREST': instance.securityDepositEarnsInterest,
      'LOAN_SECUIRTY_NEEDED': instance.loanSecurityNeeded,
      'LOAN_SECURITY': instance.loanSecurity,
      'CHARGES': instance.charges,
      'FINES': instance.fines,
      'VALID_CARD_REQUIRED': instance.validCardRequired,
      'REPAYMENT_CYCLE': instance.repaymentCycle,
      'MAX_NUM_REPAYMENTS': instance.maxNumRepayments,
      'MIN_NUM_REPAYMENTS': instance.minNumRepayments,
      'REPAYMENT_SOURCE': instance.repaymentSource,
      'DISBURSEMENT_MODE': instance.disbursementMode,
      'INSTALLMENT_FREQUENCY': instance.installmentFrequency,
      'GRACE_PERIOD': instance.gracePeriod,
      'IS_VANILLA': instance.isVanilla,
      'LOAN_OFFICER': instance.loanOfficer,
      'DISBURSEMENT_DATE_TYPE': instance.disbursementDateType,
      'DISBURSEMENT_DATE_PLUS': instance.disbursementDatePlus,
      'DISBURSEMENT_BANK': instance.disbursementBank,
      'GRACE_PERIOD_TYPE': instance.gracePeriodType,
      'EMAIL_MESSAGE_TEMPLATES': instance.emailMessageTemplates,
      'SMS_MESSAGE_TEMPLATES': instance.smsMessageTemplates,
      'PRODUCT_CHARGES': instance.productCharges,
      'SECURITY_DEPOSIT_DEDUCTIBLE': instance.securityDepositDeductible,
      'ROLLOVER_CHARGES': instance.rollOverCharges,
      'PRODUCT_FEES': instance.productFees,
      'REQUIRED_KYC': instance.requiredKYC,
      'COLLATERAL_DOCS': instance.collateralDocs,
      'REQUIRED_DOCS': instance.requiredDocs,
      'DAYS_PER_YEAR1': instance.daysPerYear1,
      'TYPE_OF_CREDIT': instance.typeOfCredit,
      'ALLOW_ROLL_OVER': instance.allowRollOver,
      'ALLOW_MERGING': instance.allowMerging,
      'MIN_REVOLVING_INSTALLMENT_PAYMENT':
          instance.minRevolvingInstallmentPayment,
      'DISBURSEMENT_ACCOUNT_NUMBER': instance.disbursementAccountNumber,
      'ALLOW_REPAYMENT_AUTODEBIT': instance.allowRepaymentAutoDebit,
      'MONTHLY_PERIOD': instance.monthlyPeriod,
      'UNDERWRITING_TEMPLATE': instance.underWritingTemplate,
      'REQUIRES_INTEREST_UPFRONT': instance.requiresInterestUpFront,
      'COMPUNDING_FREQUENCY': instance.compoundingFrequency,
      'INVESTMENT_GL_ACCOUNTS': instance.investmentGlAccounts,
      'MIN_SALARY_ACCEPTABLE': instance.minSalaryAcceptable,
      'PREFERRED_BORROWER_GENDER': instance.preferredBorrowerGender,
      'MINIMUM_RATINGS_ID': instance.minimumRatingsId,
      'NO_OF_BANK_STATEMENTS': instance.noOfBankStatements,
      'NO_OF_PAYSLIPS': instance.noOfPaySlips,
      'MINIMUM_GUARANTORS': instance.minimumGuarantors,
      'PREFERRED_BORROWER_OCCUPATION': instance.preferredBorrowerOccupation,
      'QUALIFYING_DOCUMENTS': instance.qualifyingDocuments,
      'PREFERRED_OCCUPATION_SECTOR': instance.preferredOccupationSector,
      'GUARANTOR_OCCUPATION_SECTOR': instance.guarantorOccupationSector,
      'PERIODIC_CONTRIBUTION_MAX': instance.periodicContributionMax,
      'SCHEDULE_TYPE': instance.scheduleType,
      'IS_WEB': instance.isWeb,
      'IS_MOBILE': instance.isMobile,
      'IS_EDITABLE': instance.isEditable,
      'ASSIGN_LOAN_OFFICER': instance.assignLoanOfficer,
      'LOAN_INTERVAL': instance.loanInterval,
      'DURATION_INTERVAL': instance.durationInterval,
      'INVESTMENT_SUB_CATEGORY_ID': instance.investmentSubCategoryId,
      'APPLY_PENALTY': instance.applyPenalty,
      'PENALTY_TYPE': instance.penaltyType,
      'PENALTY_VALUE': instance.penaltyValue,
      'IS_DEFAULT': instance.isDefault,
      'DEFAULT_DOCS': instance.defaultDocs,
      'QUALIFYING_DOCUMENTSLOAN_OPTIONS':
          instance.qualifyingDocumentsLoanOptions,
      'MUST_NOTIFY_ACCOUNT_OFFICER': instance.mustNotifyAccountOfficer,
      'ENABLE_GEOTAGGING': instance.enableGeoTagging,
      'GPS_RETRY': instance.gpsRetry,
      'MUST_NOFITY_ACCOUNT_OFFICER': instance.mustNotifyAccountOfficer2,
      'NOTIFICATION_EMAIL': instance.notificationEmail,
      'LOAN_OPTIONS': instance.loanOptions,
      'PRODUCT_TYPE': instance.productType,
      'INTEREST_CALCULATION_FREQUENCY': instance.interestCalculationFrequency,
      'COMPOUNDING_FREQUENCY': instance.compoundingFrequency1,
      'MINIMUM_INTEREST_BALANCE': instance.minimumInterestBalance,
      'HAS_INSURANCE': instance.hasInsurance,
      'INSURANCE_PROVIDER': instance.insuranceProvider,
      'AVAILABLE_UNITS': instance.availableUnits,
      'START_DATE': instance.startDate,
      'END_DATE': instance.endDate,
      'OFFER_CLOSING_DATE': instance.offerClosingDate,
      'ATTACHMENTS': instance.attachments,
      'APPLY_BONUS': instance.applyBonus,
      'BONUS_TYPE': instance.bonusType,
      'ENABLE_TOP_UP': instance.enableTopUp,
      'ENABLE_WITHDRAWAL': instance.enableWithdrawal,
      'ENABLE_ROLLOVER': instance.enableRollover,
      'MAX_WITHDRAWAL_PERCENTAGE': instance.maxWithdrawalPercentage,
      'signature_enabled': instance.signatureEnabled,
      'signature_left_enabled': instance.signatureLeftEnabled,
      'offer_body': instance.offerBody,
      'date_visible': instance.dateVisible,
      'offer_letter_name': instance.offerLetterName,
      'offer_letter_logo': instance.offerLetterLogo,
      'offer_letter_address': instance.offerLetterAddress,
      'offer_letter_salutation': instance.offerLetterSalutation,
      'offer_letter_body': instance.offerLetterBody,
      'offer_letter_term': instance.offerLetterTerm,
      'offer_letter_repayment': instance.offerLetterRepayment,
      'offer_letter_signature': instance.offerLetterSignature,
      'signature_left': instance.signatureLeft,
      'signature_right': instance.signatureRight,
      'offer_letter_subject': instance.offerLetterSubject,
      'offer_letter_tags': instance.offerLetterTags,
      'CURRENCY_SHORT_CODE': instance.currencyShortCode,
      'LD': instance.ld,
      'INTEREST_DURATION': instance.interestDuration,
      'ADJECTIVAL': instance.adjectival,
      'LEGAL_NAME': instance.legalName,
      'ABBREV': instance.abbr,
    };
